### ISSUE TITLE
Documentation Missing Sample SQL Query for kolide_k2_package Table

### ISSUE THREAD

**Issue by toliver38** [grendel-consulting/steampipe-plugin-kolide#58]
**Describe the bug**
The documentation for the `kolide_k2_package` table does not include a sample SQL query. Users looking to understand how to interact with the `kolide_k2_package` table via SQL queries would benefit from a concrete example. This omission makes it challenging for new users to quickly get started with querying the table.

**To Reproduce**
1. Go to 'https://github.com/grendel-consulting/steampipe-plugin-kolide/blob/main/docs/tables/kolide_k2_package.md'
2. Scroll down to the section where a sample query might typically be found.
3. Notice the absence of a 'Sample Queries' section or any SQL example.

**Expected behavior**
I expected to find at least one sample SQL query demonstrating how to select data from the `kolide_k2_package` table. For example, a simple query to fetch all columns for all records, or a more complex query illustrating how to filter records based on certain conditions.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Adding sample queries to the documentation would significantly improve the usability of the documentation for new users and serve as a quick reference for more experienced users. Providing examples of both simple and complex queries could help demonstrate the table's capabilities and the types of insights users can gain from the data.

**Comment by ramirezj** [comment]
Do the examples in #60 help clarify @toliver38 ?

**Comment by toliver38** [comment]
Looks great!
