### ISSUE TITLE
Initial Plugin Review

### ISSUE THREAD

**Issue by khushboo9024** [grendel-consulting/steampipe-plugin-kolide#59]
Thanks @grendel-consulting for this new plugin. Great work 🎉 !!

The basic structure looks good so far. While using the plugin, we did come up with a few suggestions based on our best practices:

`Missing files`

- Basic git template files

`renovate.json`

I think we don't need this folder so we can remove it

`docs/index.md`
- The website URL of `Kolide` is missing in `# Kolide + Steampipe` section
- Please fix the formatting in `### Rate Limiting` section as triple backticks (```) are missing for the block of code. 

`docs/tables/*`

- Each query should end with a ;
- Each description should end with a `.`
- The example queries in the doc look a bit light. Could you please add a few more example queries for tables, especially for the `kolide_k2_package` table?
- It looks like the SQL query provided is not correctly formatted within an SQL code block. To ensure proper formatting it's important to enclose the SQL code within triple backticks, followed by the SQL identifier.

`Makefile`

- Could you please update the Makefile to follow the format of the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/Makefile)

**Comment by ramirezj** [comment]
> `Makefile`
> 
> * Could you please update the Makefile to follow the format of the [namecheap plugin](https://github.com/turbot/steampipe-plugin-namecheap/blob/main/Makefile)

@khushboo9024, I have followed the pattern used in the [aws plugin](https://github.com/turbot/steampipe-plugin-aws/blob/main/Makefile) because this plugin (indirectly) uses the Golang `net` module and statically-linking it is potentially safer. Let me know you thoughts

**Comment by ramirezj** [comment]
Everything else I am addressing in #60 @khushboo9024 , complete bar the further examples so far

**Comment by misraved** [comment]
@ramirezj thank you once again for the new plugin 👍!!

Few questions/suggestions before we proceed to release the plugin on the hub:
- Is there a specific reason for including `k2` in the table nomenclature? I was looking at the API docs but couldn't find any reference. Could you please share relevant API docs that clearly differentiate between the K1 and K2 API versions?
- Could you please update the README file to stay more consistent with the current set of plugins that we have today? For e.g. https://github.com/turbot/steampipe-plugin-aws/blob/main/README.md
- Is there a specific reason for building the `netgo` package in the Make file? https://github.com/grendel-consulting/steampipe-plugin-kolide/blob/main/Makefile#L8
- How has the Steampipe CLI behaved with go version `1.21.9`? Does the plugin work as per expectation? We haven't tested out the changes in detail, so curious to know if you faced any particular issue during the plugin development process.

**Comment by ramirezj** [comment]
> * Is there a specific reason for including `k2` in the table nomenclature? I was looking at the API docs but couldn't find any reference. Could you please share relevant API docs that clearly differentiate between the K1 and K2 API versions?

Per the remarks on [the API token format](https://www.kolide.com/docs/developers/api#api-token-format) the token prefix is tied to the original K2 product Kolide offered; happy to rename if you feel this isn't in alignment

**Comment by ramirezj** [comment]
> * Could you please update the README file to stay more consistent with the current set of plugins that we have today? For e.g. https://github.com/turbot/steampipe-plugin-aws/blob/main/README.md

Are there specific elements to include or exclude?

**Comment by ramirezj** [comment]
> * Is there a specific reason for building the `netgo` package in the Make file? https://github.com/grendel-consulting/steampipe-plugin-kolide/blob/main/Makefile#L8

Following the pattern in the Steampipe AWS  plugin, we want consistent behaviour when using network connections, hence needing to explicitly bake in `netgo` whwen building on macOS

**Comment by ramirezj** [comment]
> * How has the Steampipe CLI behaved with go version `1.21.9`? Does the plugin work as per expectation? We haven't tested out the changes in detail, so curious to know if you faced any particular issue during the plugin development process.

At the moment it is working as per expected on Golang `1.21.9`. Not adverse or unexpected results

**Comment by ramirezj** [comment]
Everything should be addressed @misraved
